openapi: 3.1.3
info:
    title: NPM Open APIs
    description: NPM Open APIs
    version: '1.0'
servers:
    - url: https://api.npmjs.org
paths:
    /downloads/point/{period}:
        get:
            description: Gets the downloads per day for a given period for all packages.
            parameters:
                - in: path
                  name: period
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Registry downloads metadata info
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RegistryDownloads'
                            examples:
                                '0':
                                    value: >-
                                        {
                                          "downloads": [
                                            {
                                              "day": "2014-02-27",
                                              "downloads": 1904088
                                            },
                                            {
                                              "day": "2014-03-04",
                                              "downloads": 7904294
                                            }
                                          ],
                                          "start": "2014-02-25",
                                          "end": "2014-03-04",
                                          "package": "somepackage"
                                        }
    /downloads/point/{period}/{packageName}:
        get:
            description: Gets the downloads per day for a given period for a specific package.
            parameters:
                - in: path
                  name: period
                  required: true
                  schema:
                      type: string
                - in: path
                  name: packageName
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Package downloads metadata info
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PackageDownloads'
                            examples:
                                '0':
                                    value: >-
                                        {
                                          "downloads": 31623,
                                          "start": "2014-01-01",
                                          "end": "2014-01-31",
                                          "package": "jquery"
                                        }
    /downloads/range/{period}:
        get:
            description: Gets the downloads per day for a given period for all packages.
            parameters:
                - in: path
                  name: period
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Registry downloads metadata info
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DailyRegistryDownloads'
                            examples:
                                '0':
                                    value: >-
                                        {
                                          "downloads": [
                                            {
                                              "day": "2014-02-27",
                                              "downloads": 1904088
                                            },
                                            {
                                              "day": "2014-03-04",
                                              "downloads": 7904294
                                            }
                                          ],
                                          "start": "2014-02-25",
                                          "end": "2014-03-04"
                                        }
    /downloads/range/{period}/{packageName}:
        get:
            description: Gets the downloads per day for a given period for a specific package.
            parameters:
                - in: path
                  name: period
                  required: true
                  schema:
                      type: string
                - in: path
                  name: packageName
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Package downloads metadata info
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DailyPackageDownloads'
                            examples:
                                '0':
                                    value: >-
                                        {
                                          "start": "2022-09-25",
                                          "end": "2022-10-01",
                                          "package": "jquery",
                                          "downloads": [
                                              {
                                                  "downloads": 214190,
                                                  "day": "2022-09-25"
                                              },
                                              {
                                                  "downloads": 1146822,
                                                  "day": "2022-09-26"
                                              },
                                              {
                                                  "downloads": 1115359,
                                                  "day": "2022-09-27"
                                              },
                                              {
                                                  "downloads": 1094660,
                                                  "day": "2022-09-28"
                                              },
                                              {
                                                  "downloads": 1065723,
                                                  "day": "2022-09-29"
                                              },
                                              {
                                                  "downloads": 894018,
                                                  "day": "2022-09-30"
                                              },
                                              {
                                                  "downloads": 220794,
                                                  "day": "2022-10-01"
                                              }
                                          ]
                                        }
    /versions/{packageName}/last-week:
        get:
            description: >-
                Download count for specific versions of a package. It's only available for the previous 7 days.

                Note: for scoped packages, the `/` needs to be percent encoded. (`@slack/client` -> `@slack%2Fclient`).
            parameters:
                - in: path
                  name: packageName
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Package download count for specific versions.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PackageVersionsDownloadCount'
                            examples:
                                '0':
                                    value: >-
                                        {
                                          "package": "fastify",
                                          "downloads": {
                                            "3.1.1": 1409,
                                            "3.27.2": 7670,
                                            "2.14.1": 2824,
                                            "3.24.0": 4475,
                                            "4.0.0": 652,
                                            "3.20.1": 18007,
                                            "3.28.0": 48612,
                                            "4.3.0": 23722
                                          }
                                        }

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
    schemas:
        PackageVersionsDownloadCount:
            type: object
            description: Package download count for specific versions.
            required:
                - package
                - downloads
            properties:
                package:
                    type: string
                    description: Package name
                    nullable: false
                    readOnly: true
                downloads:
                    type: object
                    description: A map containing the package version as key and the download count as value.
                    additionalProperties:
                        type: integer
                        nullable: false

        RegistryDownloads:
            description: Lists the number of downloads for the registry in a given time period.
            type: object
            required:
                - downloads
                - start
                - end
            properties:
                downloads:
                    type: integer
                    description: Total number of downloads
                    nullable: false
                    readOnly: true
                start:
                    type: string
                    format: date
                    description: Date of the first day (inclusive)
                    nullable: false
                    readOnly: true
                end:
                    type: string
                    format: date
                    description: Date of the last day (inclusive)
                    nullable: false
                    readOnly: true

        PackageDownloads:
            description: Lists the number of downloads for a package in a given time period.
            allOf:
                - $ref: '#/components/schemas/RegistryDownloads'
                - type: object
                  required:
                      - package
                  properties:
                      package:
                          type: string
                          description: Package name
                          nullable: false
                          readOnly: true

        DownloadsPerDay:
            description: Lists the number of downloads in a given day.
            type: object
            required:
                - downloads
                - day
            properties:
                downloads:
                    type: integer
                    nullable: false
                    readOnly: true
                day:
                    type: string
                    format: date
                    nullable: false
                    readOnly: true

        DailyRegistryDownloads:
            description: Lists the number of downloads for a package for each day in a given time period.
            type: object
            required:
                - downloads
                - start
                - end
            properties:
                downloads:
                    type: array
                    description: Download counts per day
                    nullable: false
                    readOnly: true
                    items:
                        $ref: '#/components/schemas/DownloadsPerDay'
                start:
                    type: string
                    format: date
                    description: Date of the first day (inclusive)
                    nullable: false
                    readOnly: true
                end:
                    type: string
                    format: date
                    description: Date of the last day (inclusive)
                    nullable: false
                    readOnly: true

        DailyPackageDownloads:
            description: Lists the number of downloads for a package for each day in a given time period.
            allOf:
                - $ref: '#/components/schemas/DailyRegistryDownloads'
                - type: object
                  required:
                      - package
                  properties:
                      package:
                          type: string
                          description: Package name
                          nullable: false
                          readOnly: true
