name: Check Code Quality

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache turbo build setup
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Get pnpm store directory
              id: pnpm-store
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run ESLint check
              run: pnpm lint

    test:
        needs: lint
        strategy:
            matrix:
                os:
                    [
                        ubuntu-24.04,
                        ubuntu-22.04,
                        macos-15,
                        macos-14,
                        windows-2025,
                        windows-2022,
                    ]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache turbo build setup
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Get pnpm store directory
              id: pnpm-store
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install package managers
              run: |
                  corepack enable
                  corepack install npm@10.7.0 -g
                  corepack install yarn@4.9.2 -g

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Run tests
              run: pnpm test
